name: airbnb
services:
  web:
    build: ./airbnb_backend
    image: airbnb-backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    container_name: airbnb_backend
    volumes:
      - ./airbnb_backend:/usr/src/airbnb_backend
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: airbnb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  postgres_data:
