# Generated by Django 5.1.4 on 2025-04-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_user_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reservations',
        ),
    ]
